def Test =
  try ()
  catch {
    case x: Throwable if x.getMessage `contains` "error" => ???
  }